import type { Metadata } from "next";
import { Poppins } from "next/font/google";

// Load Inter and Poppins fonts
// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "700"] });

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full bg-gray-100  ${poppins.className} overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
